fix concatenation of anything_else
qntm/greenery pull request #53
Opened 2021-05-03 04:24 UTC by doni69

When concatenating fsms with differing alphabets, symbols from the others' alphabets do not map as if they were anything_else.

For example:
```
# [^a]
fsm1=fsm(
  alphabet={"a",anything_else},
  states={0,1},
  initial=0,
  finals={1},
  map={0:{anything_else:1}}
# .
fsm2=fsm(
  alphabet={anything_else},
  states={0,1},
  initial=0,
  finals={1},
  map={0:{anything_else:1}}
  )
# [^a].
assert (fsm1+fsm2).accepts("ba") # Fails
```
Looking at the concatenated result,
```
>>> print(fsm1+fsm2)
 name final? a anything_else 
------------------------------
* 0    False    1             
  1    False    2             
  2    True                   
```
We see that "a" which is not in fsm2's alphabet does not get treated as if it were anything_else as it should.
To fix this, we check to see if the character is not in the alphabet and create the same transition as anything_else (if anything_else has such a transition).

This however doesn't seem to be an issue when concatenated through the lego module though.
```
>>> l1=lego.parse("[^a]")
>>> l2=lego.parse(".")
>>> print(l1.to_fsm()+l2.to_fsm())
  name final? a anything_else 
------------------------------
* 0    False    1             
  1    False    2             
  2    True                  
>>> print((l1+l2).to_fsm())
  name final? a anything_else 
------------------------------
* 0    False    1             
  1    False  2 2             
  2    True                   
```

2021-05-03 23:41 UTC, qntm requested changes
Great spot on that bug, thank you! Fix looks good too. However, can you please add a unit test for this case, so this doesn't regress in the future?

2021-05-04 01:22 UTC, doni69 commented
The above example test has been added

2021-05-04 18:11 UTC, qntm approved these changes

2021-05-04 18:11 UTC, merged

2021-05-04 18:30 UTC, qntm commented
This fix is in `greenery` version 3.3.2.